### ISSUE TITLE
Project Structure and Naming

### ISSUE THREAD

**Issue by ayimdomnic** [GithakaMbui/Data-Structures-And-Algorithms-in-JS#1]
Hey @GithakaMbui 

Kudos on getting to basics with JavaScript and learning how to solve JavaScript algorithm problems.

Nonetheless, I have a few pointers to get to you good from the word go!
I am sure you are aware of the lawlessness that comes with JavaScript and that is fine. but great code doesn't only solve the problem it also makes it easier for whoever is reusing it to understand what exactly is going on with the solution

You could perhaps start by grouping the algorithms to folders eg `arrays, strings, etc` and using consistent file naming through out the code.

I would recommend you go through[Uncle Bob's site](http://cleancoder.com) and get some pointers on the above

Keep up the good work!

PS: I could make a fork to this repository and implement some of the pointers mentioned above if you don't mind.

All The Best & Good Work!

**Comment by GithakaMbui** [comment]
Thanks. Go ahead and fork the repo. I would appreciate your pointers on how I should better organize my code
